### ISSUE TITLE
The website needs some love ..

### ISSUE THREAD

**Issue by skx** [xen-tools/website#1]
I don't have any real involvement these days, but I'd be willing to make the changes described below, if that would be useful:

* The virtual-includes are all broken
   * The source repository has them stored beneath `/includes`, but referred to as `/inc`, e.g. 
       * `<!--#include virtual="/inc/top-menu.html" -->`
* ~~The /donate/ page should become a 404.~~
* The footers are inconsistent.
* ~~The META-tag doesn't need an author any more.~~
* ~~The xen-shell area needs a lot of tweaks.~~
   * ~~Remove links to hg + cvs.~~

If I were ambitious I'd say "the layout sucks" and rewrite it in hugo/etc, but I think that might be a step too far !

(Filed this against gitlab first, which seemed to be the canonical repo, but looking again _this_ repo was updated most recently.  ~~Clarification on which is preferred wouldn't hurt~~ :) )

**Comment by xtaran** [comment]
Thanks for the detailed list.

> The virtual-includes are all broken 

Indeed. I though never missed these parts.

> The /donate/ page should become a 404.

Definitely. Will be done in a second.

> The footers are inconsistent.

Will be fixed once the site is changed to be statically generated. Surely not beforehand.

> The META-tag doesn't need an author any more.

It at least should change. (Although it probably is still correct for most of the pages.)

> The xen-shell area needs a lot of tweaks.

IMHO it basically should say "Here's the last tar-ball, here's the VCS history, do what you want, otherwise it's abandoned".

> If I were ambitious I'd say "the layout sucks"

It does. At least from nowadays point of view. :-)

> and rewrite it in hugo/etc, but I think that might be a step too far !

Have a look into the `wml` branch. That's where I started. But even only the converting to a static site generator was way more work than I thought and the contents in that branch got quickly out of date, so at some point, I decided, that for now it's easier to keep the layout and just update contents where needed.

> (Filed this against gitlab first,

Couldn't find any e-mail notification for that.

> which seemed to be the canonical repo,

Not really. For quite a while I was undecided, but Gitlab's UI started to suck more and more and then I decided to use GitHub despite it's not completely Open Source, but otherwise far more appealing.

> but looking again this repo was updated most recently. Clarification on which is preferred wouldn't hurt :) )

Well, at least in the code repositories it's clearly stated. I never bothered to do that for the website as I really really never expected that anyone will ever contribute. :-)

**Comment by skx** [comment]
> Indeed. I though never missed these parts.

Copy and paste inline, I think.  It does make things more navigateable.

> IMHO it basically should say "Here's the last tar-ball, here's the VCS history, do what you want, otherwise it's abandoned".

That's probably best.

Also, as another minor issue - ~~one of the twitter links is a spam account these days~~.  Not in front of my real computer so I don't have the link to hand, should be obvious if you look though :)

**Comment by xtaran** [comment]
> Also, as another minor issue - one of the twitter links is a spam account these days.

Thanks for that hint, too. Removed.

**Comment by xtaran** [comment]
Ok, I think I've fixed all low hanging fruits and urgent issues now.

There are two tasks left:

- [x] Revamp the xen-shell area.
- [ ] Convert to a static site generator. This includes:
  * Consistent footers
  * Fixing of the includes. (I don't want to fix that before hand because it would cause inconsistencies over time which make it even harder to convert the site to a static site generator, hence I'd leave them as is as a reminder.)
  * New layout/design.

**Comment by skx** [comment]
I've given you a pull-request for the the xen-shell cleanup.  I don't think I missed anything important, but if I did I'll leave it with you.
